
//GET STUDENT profile data
export const GET_STUDENT_PROFILE_LOADING ="GET_STUDENT_PROFILE_LOADING";
export const GET_STUDENT_PROFILE_SUCCESS ="GET_STUDENT_PROFILE_SUCCESS ";
export const GET_STUDENT_PROFILE_ERROR ="GET_STUDENT_PROFILE_ERROR";

//UPDATE STUDENT profile data
export const UPDATE_STUDENT_PROFILE_LOADING ="UPDATE_STUDENT_PROFILE_LOADING";
export const UPDATE_STUDENT_PROFILE_SUCCESS ="UPDATE_STUDENT_PROFILE_SUCCESS ";
export const UPDATE_STUDENT_PROFILE_ERROR ="UPDATE_STUDENT_PROFILE_ERROR";

//GET GENERAL Plan
export const GET_GENERAL_PLAN_LOADING ="GET_GENERAL_PLAN_LOADING";
export const GET_GENERAL_PLAN_SUCCESS ="GET_GENERAL_PLAN_SUCCESS ";
export const GET_GENERAL_PLAN_ERROR ="GET_GENERAL_PLAN_ERROR";

//GET MY Plans
export const GET_MY_PLANS_LOADING ="GET_MY_PLANS_LOADING";
export const GET_MY_PLANS_SUCCESS ="GET_MY_PLANS_SUCCESS ";
export const GET_MY_PLANS_ERROR ="GET_MY_PLANS_ERROR";

//getOneCustomPlan
export const GET_ONE_CUSTOM_PLAN_LOADING ="GET_ONE_CUSTOM_PLAN_LOADING";
export const GET_ONE_CUSTOM_PLAN_SUCCESS ="GET_ONE_CUSTOM_PLAN_SUCCESS ";
export const GET_ONE_CUSTOM_PLAN_ERROR ="GET_ONE_CUSTOM_PLAN_ERROR";

// GET STUDENT SUBJECT
export const GET_STUDENT_SUBJECTS_LOADING = "GET_STUDENT_SUBJECTS_LOADING";
export const GET_STUDENT_SUBJECTS_SUCCESS ="GET_STUDENT_SUBJECTS_SUCCESS";
export const GET_STUDENT_SUBJECTS_ERROR ="GET_STUDENT_SUBJECTS_ERROR";

//GET HELP
export const GET_STUDENT_HELP_LOADING ="GET_STUDENT_HELP_LOADING";
export const GET_STUDENT_HELP_SUCCESS ="GET_STUDENT_HELP_SUCCESS";
export const GET_STUDENT_HELP_ERROR ="GET_STUDENT_HELP_ERROR";

//CREATE CUSTOM PLAN ACTION
export const CREATE_CUSTOM_PLAN_LOADING ="CREATE_CUSTOM_PLAN_LOADING";
export const CREATE_CUSTOM_PLAN_SUCCESS ="CREATE_CUSTOM_PLAN_SUCCESS";
export const CREATE_CUSTOM_PLAN_ERROR ="CREATE_CUSTOM_PLAN_ERROR";

//UPDATE CUSTOM PLAN
export const UPDATE_CUSTOM_PLAN_LOADING ="UPDATE_CUSTOM_PLAN_LOADING";
export const UPDATE_CUSTOM_PLAN_SUCCESS ="UPDATE_CUSTOM_PLAN_SUCCESS";
export const UPDATE_CUSTOM_PLAN_ERROR ="UPDATE_CUSTOM_PLAN_ERROR";

//DELETE CUSTOM PLAN
export const DELETE_CUSTOM_PLAN_LOADING ="DELETE_CUSTOM_PLAN_LOADING";
export const DELETE_CUSTOM_PLAN_SUCCESS ="DELETE_CUSTOM_PLAN_SUCCESS";
export const DELETE_CUSTOM_PLAN_ERROR ="DELETE_CUSTOM_PLAN_ERROR";