//######################Subjet#######################

//create Subject
export const CREATE_SUBJECT_LOADING = "CREATE_SUBJECT_LOADING";
export const CREATE_SUBJECT_SUCCESS = "CREATE_SUBJECT_SUCCESS";
export const CREATE_SUBJECT_ERROR = "CREATE_SUBJECT_ERROR";

//update Subject
export const UPDATE_SUBJECT_LOADING = "UPDATE_SUBJECT_LOADING";
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS";
export const UPDATE_SUBJECT_ERROR = "UPDATE_SUBJECT_ERROR";

//delete Subject
export const DELETE_SUBJECT_LOADING = "DELETE_SUBJECT_LOADING";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_ERROR = "DELETE_SUBJECT_ERROR";

//######################SubMajor###############
//create SubMajor
export const CREATE_SUB_MAJOR_LOADING = "CREATE_SUB_MAJOR_LOADING";
export const CREATE_SUB_MAJOR_SUCCESS = "CREATE_SUB_MAJOR_SUCCESS";
export const CREATE_SUB_MAJOR_ERROR = "CREATE_SUB_MAJOR_ERROR";

//update SubMajor
export const UPDATE_SUB_MAJOR_LOADING = "UPDATE_SUB_MAJOR_LOADING";
export const UPDATE_SUB_MAJOR_SUCCESS = "UPDATE_SUB_MAJOR_SUCCESS";
export const UPDATE_SUB_MAJOR_ERROR = "UPDATE_SUB_MAJOR_ERROR";

//delete SubMajor
export const DELETE_SUB_MAJOR_LOADING = "DELETE_SUB_MAJOR_LOADING";
export const DELETE_SUB_MAJOR_SUCCESS = "DELETE_SUB_MAJOR_SUCCESS";
export const DELETE_SUB_MAJOR_ERROR = "DELETE_SUB_MAJOR_ERROR";

//######################SubSubject###############
//create SubSubject
export const CREATE_SUB_SUBJECT_LOADING = "CREATE_SUB_SUBJECT_LOADING";
export const CREATE_SUB_SUBJECT_SUCCESS = "CREATE_SUB_SUBJECT_SUCCESS";
export const CREATE_SUB_SUBJECT_ERROR = "CREATE_SUB_SUBJECT_ERROR";

//update SubSubject
export const UPDATE_SUB_SUBJECT_LOADING = "UPDATE_SUB_SUBJECT_LOADING";
export const UPDATE_SUB_SUBJECT_SUCCESS = "UPDATE_SUB_SUBJECT_SUCCESS";
export const UPDATE_SUB_SUBJECT_ERROR = "UPDATE_SUB_SUBJECT_ERROR";

//delete SubSubject
export const DELETE_SUB_SUBJECT_LOADING = "DELETE_SUB_SUBJECT_LOADING";
export const DELETE_SUB_SUBJECT_SUCCESS = "DELETE_SUB_SUBJECT_SUCCESS";
export const DELETE_SUB_SUBJECT_ERROR = "DELETE_SUB_SUBJECT_ERROR";
